### ISSUE TITLE
Minor fix for improved visualisation: axis tight and fixed colour axis

### ISSUE THREAD

**Issue by luraess** [omlins/libdiffusion#4]
https://github.com/omlins/libdiffusion/blob/3ac666dca4de233f79be647233ae859ee5a10fae/src/Diffusion.jl#L52
may be adapted to
```Julia
heatmap(T_v, aspect_ratio=1, xlims=(1, nx_v), ylims=(1, ny_v), clims=(0, amp_T)); frame(anim)
```
for fixing the colorbar axis to `0` and `amp_T` range and for displaying tight axis referring to the numerical grid resolution `nx_v` and `ny_v` (to be potentially further adapted if the `x` and `y` axis `lims` should refer to the `lx` and `ly` extends).

**Comment by omlins** [comment]
Done
